# eq_cosplay_metrics: {"peq_rmse": 1.2328500088889047, "combined_rmse": 0.13545960980923738, "fir_rmse": 0.13545960980923735, "response_peak": 18.318555930737272, "response_valley": -4.917064000615103, "iir_response_peak": 13.815198725131598, "fir_response_peak": 18.318555930737272, "level_offset_db": -0.2686602660911107, "fir_n_taps": 8192, "use_fir": true}
---
devices:
  samplerate: 48000
  chunksize: 1024
  capture:
    type: CoreAudio
    channels: 2
    device: "BlackHole 2ch"
  playback:
    type: CoreAudio
    channels: 2
    device: "外置耳机"

filters:
  preamp_gain:
    type: Gain
    parameters:
      gain: -18.51855593073727
      inverted: false

  fir_left:
    type: Conv
    parameters:
      type: Wav
      filename: "/Users/zhuyongfei/Desktop/eq_cosplay/presets/cosplay_Sony_MDR-EX1000_RikudouGoku_to_Sony_WH-1000XM4_oratory1990_fir_left.wav"
      channel: 0

  fir_right:
    type: Conv
    parameters:
      type: Wav
      filename: "/Users/zhuyongfei/Desktop/eq_cosplay/presets/cosplay_Sony_MDR-EX1000_RikudouGoku_to_Sony_WH-1000XM4_oratory1990_fir_right.wav"
      channel: 0

  peq_01:
    type: Biquad
    parameters:
      type: Lowshelf
      freq: 30.0
      gain: 3.9
      q: 1.0
  peq_02:
    type: Biquad
    parameters:
      type: Peaking
      freq: 41.1
      gain: 5.27
      q: 0.63
  peq_03:
    type: Biquad
    parameters:
      type: Peaking
      freq: 119.1
      gain: 4.4
      q: 1.03
  peq_04:
    type: Biquad
    parameters:
      type: Peaking
      freq: 415.4
      gain: -3.53
      q: 1.16
  peq_05:
    type: Biquad
    parameters:
      type: Peaking
      freq: 600.8
      gain: 3.88
      q: 1.42
  peq_06:
    type: Biquad
    parameters:
      type: Peaking
      freq: 2098.1
      gain: -6.79
      q: 2.23
  peq_07:
    type: Biquad
    parameters:
      type: Peaking
      freq: 3821.3
      gain: 10.0
      q: 1.5
  peq_08:
    type: Biquad
    parameters:
      type: Peaking
      freq: 6152.7
      gain: -7.66
      q: 2.33
  peq_09:
    type: Biquad
    parameters:
      type: Peaking
      freq: 12960.7
      gain: 10.0
      q: 1.93
  peq_10:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 14000.0
      gain: 10.0
      q: 1.4

pipeline:
  - type: Filter
    channels: [0]
    names:
      - preamp_gain
      - fir_left
      - peq_01
      - peq_02
      - peq_03
      - peq_04
      - peq_05
      - peq_06
      - peq_07
      - peq_08
      - peq_09
      - peq_10
  - type: Filter
    channels: [1]
    names:
      - preamp_gain
      - fir_right
      - peq_01
      - peq_02
      - peq_03
      - peq_04
      - peq_05
      - peq_06
      - peq_07
      - peq_08
      - peq_09
      - peq_10
