# eq_cosplay_metrics: {"peq_rmse": 1.0016055706033062, "combined_rmse": 0.09237030491807877, "fir_rmse": 0.09237030491807875, "response_peak": 7.795870256759932, "response_valley": -11.884827204801123, "fir_response_peak": 7.795870256759932, "level_offset_db": 0.5575387801581267, "fir_n_taps": 8192, "use_fir": true}
---
devices:
  samplerate: 48000
  chunksize: 1024
  capture:
    type: CoreAudio
    channels: 2
    device: "BlackHole 2ch"
  playback:
    type: CoreAudio
    channels: 2
    device: "外置耳机"

filters:
  preamp_gain:
    type: Gain
    parameters:
      gain: -7.9958702567599325
      inverted: false

  fir_left:
    type: Conv
    parameters:
      type: Wav
      filename: "/Users/zhuyongfei/Desktop/eq_cosplay/presets/cosplay_Sony_WH-1000XM4_oratory1990_to_AKG_K701_oratory1990_fir_left.wav"
      channel: 0

  fir_right:
    type: Conv
    parameters:
      type: Wav
      filename: "/Users/zhuyongfei/Desktop/eq_cosplay/presets/cosplay_Sony_WH-1000XM4_oratory1990_to_AKG_K701_oratory1990_fir_right.wav"
      channel: 0

  peq_01:
    type: Biquad
    parameters:
      type: Lowshelf
      freq: 28.8
      gain: -6.38
      q: 0.83
  peq_02:
    type: Biquad
    parameters:
      type: Peaking
      freq: 33.8
      gain: -7.06
      q: 0.35
  peq_03:
    type: Biquad
    parameters:
      type: Peaking
      freq: 117.1
      gain: -3.39
      q: 1.61
  peq_04:
    type: Biquad
    parameters:
      type: Peaking
      freq: 436.2
      gain: 6.12
      q: 1.03
  peq_05:
    type: Biquad
    parameters:
      type: Peaking
      freq: 591.8
      gain: -6.11
      q: 1.24
  peq_06:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1434.6
      gain: -3.75
      q: 3.15
  peq_07:
    type: Biquad
    parameters:
      type: Peaking
      freq: 2352.5
      gain: 10.0
      q: 1.65
  peq_08:
    type: Biquad
    parameters:
      type: Peaking
      freq: 3930.4
      gain: -5.92
      q: 1.15
  peq_09:
    type: Biquad
    parameters:
      type: Peaking
      freq: 6479.1
      gain: 6.91
      q: 3.97
  peq_10:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 6878.3
      gain: -1.56
      q: 1.4

pipeline:
  - type: Filter
    channels: [0]
    names:
      - preamp_gain
      - fir_left
      - peq_01
      - peq_02
      - peq_03
      - peq_04
      - peq_05
      - peq_06
      - peq_07
      - peq_08
      - peq_09
      - peq_10
  - type: Filter
    channels: [1]
    names:
      - preamp_gain
      - fir_right
      - peq_01
      - peq_02
      - peq_03
      - peq_04
      - peq_05
      - peq_06
      - peq_07
      - peq_08
      - peq_09
      - peq_10
